ID: 24396
Title: In distributed queries, `ORDER BY expr(x)` with `LIMIT BY x` throws exception about not found column
Description:
**Does it reproduce on recent release?**
Yes

**How to reproduce**
Clickhouse version 21.6

```
SELECT *
FROM clusterAllReplicas('test_cluster_two_shards', view(
    SELECT *
    FROM numbers(10)
))
ORDER BY number IN (1, 2) ASC
LIMIT 1 BY number

Query id: b4caff57-9ecc-45e1-9e72-39f68530cd13


0 rows in set. Elapsed: 0.002 sec.

Received exception from server (version 21.6.1):
Code: 8. DB::Exception: Received from localhost:9000. DB::Exception: Cannot find column `in(number, tuple(1, 2))` in source stream.


SELECT *
FROM clusterAllReplicas('test_cluster_two_shards', view(
    SELECT *
    FROM numbers(10)
))
ORDER BY number IN (1, 2) ASC

Query id: 7fedc826-0bf2-407d-bf19-94dfe77e5a16

┌─number─┐
│      0 │
│      3 │
│      4 │
│      5 │
│      6 │
│      7 │
│      8 │
│      9 │
│      0 │
│      3 │
│      4 │
│      5 │
│      6 │
│      7 │
│      8 │
│      9 │
│      1 │
│      2 │
│      1 │
│      2 │
└────────┘

20 rows in set. Elapsed: 0.006 sec.

SELECT *
FROM numbers(10)
ORDER BY number IN (1, 2) ASC
LIMIT 1 BY number

Query id: 90c6a735-baa5-4de5-90b9-de6c9cee40a4

┌─number─┐
│      0 │
│      3 │
│      4 │
│      5 │
│      6 │
│      7 │
│      8 │
│      9 │
│      1 │
│      2 │
└────────┘

```

