ID: 14581
Title: Error connecting to db with RTree Index
Description:
### What happens?

I created a table with geometry column and add rtree index. I can make a query from the table just like usual, the issue came up when I tried to reconnect to the db.

```
---------------------------------------------------------------------------
InternalException                         Traceback (most recent call last)
Cell In[3], [line 2](vscode-notebook-cell:?execution_count=3&line=2)
      [1](vscode-notebook-cell:?execution_count=3&line=1) # Create or connect to an in-memory DuckDB database
----> [2](vscode-notebook-cell:?execution_count=3&line=2) conn = duckdb.connect(
      [3](vscode-notebook-cell:?execution_count=3&line=3)     database=str(DB_DIR/'datareading.db'),
      [4](vscode-notebook-cell:?execution_count=3&line=4)     )
      [6](vscode-notebook-cell:?execution_count=3&line=6) # Install and load the necessary extensions
      [7](vscode-notebook-cell:?execution_count=3&line=7) conn.execute("INSTALL 'spatial'")

InternalException: INTERNAL Error: Failure while replaying WAL file "path/to/db/datareading.db.wal": Index type "RTREE" not recognized
This error signals an assertion failure within DuckDB. This usually occurs due to unexpected conditions or errors in the program's logic.
For more information, see https://duckdb.org/docs/dev/internal_errors
```

### To Reproduce

```python
import duckdb

# Create or connect to an in-memory DuckDB database
conn = duckdb.connect(
    database=str(DB_DIR/'datareading.db'),
    )

# Install and load the necessary extensions
conn.execute("INSTALL 'spatial'")
conn.execute("LOAD 'spatial'")

# Set S3 region
conn.execute("SET s3_region='us-west-2';")

bbox = {'min_x': 106.73483276367188,'min_y': -6.681308269500732,'max_x': 106.84856414794922,'max_y': -6.514328956604004})

conn.sql(
f"""--sql
CREATE TABLE IF NOT EXISTS bogor_building AS

WITH
bogor_building_bbox as (
    SELECT
        id,
        level,
        height,
        names AS names,
        sources[1].dataset AS primary_source,
        sources AS sources,
        geometry
    FROM
        read_parquet('s3://overturemaps-us-west-2/release/2024-07-22.0/theme=buildings/type=*/*', filename=true, hive_partitioning=1) buildings
    WHERE
        TRUE
        AND bbox.xmin > '{xmin}'
        AND bbox.xmax < '{xmax}'
        AND bbox.ymin > '{ymin}'
        AND bbox.ymax < '{ymax}'
)

SELECT
    *
FROM
    bogor_building_bbox build_bbox
WHERE
    TRUE
    AND ST_Within(build_bbox.geometry, (SELECT geometry FROM indo_admin WHERE id = '{kota_bogor_geom_id}'));
""")

conn.sql(
"""--sql
CREATE TABLE IF NOT EXISTS r_bogor_building AS SELECT * FROM bogor_building;
CREATE INDEX my_idx ON r_bogor_building USING RTREE (geometry);
"""
)
```

### OS:

Windows

### DuckDB Version:

1.1.1

### DuckDB Client:

Python

### Hardware:

_No response_

### Full Name:

Amri Rasyidi

### Affiliation:

-

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have