ID: 16135
Title: default_connection: When closed, default_connection() returns the closed connection
Description:
### What happens?

Related to https://github.com/duckdb/duckdb/pull/13442, some oddities occur when using `default_connection()`. 

The main thing is: when the default_connection is closed, the closed connection continues to return. I would've expected it to reset as if no connection, and return a new connection on next call.

Basically, anything that closes a default_connection leads to a bad state. How should things work if the default_connection is closed? Anyway, I think https://github.com/duckdb/duckdb/pull/13442#issuecomment-2293597747 is probably on point, default_connection leads to weirdness. 


### To Reproduce


```py
import duckdb
with duckdb.default_connection() as con:
    con.execute("select version()")
with duckdb.default_connection() as con:
    con.execute("select version()")
```
| ConnectionException: Connection Error: Connection already closed!


### OS:

Windows

### DuckDB Version:

1.2.0

### DuckDB Client:

Python

### Hardware:

_No response_

### Full Name:

Paul T

### Affiliation:

Iqmo

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a nightly build

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [x] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [x] Yes, I have