ID: 29708
Title: TiDB is not resulting error when max_allowed_packet is breached 
Description:
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
```sql
drop table if exists t1;
CREATE TABLE t1 (a text)character set utf8 ;
INSERT INTO t1 VALUES  (REPEAT(0125,200000000));
select * from t1;
```
### 2. What did you expect to see? (Required)
```sql
mysql> INSERT INTO t1 VALUES  (REPEAT(0125,200000000));
ERROR 1301 (HY000): Result of repeat() was larger than max_allowed_packet (2048) - truncated
mysql> select * from t1;
Empty set (0.00 sec)
```
### 3. What did you see instead (Required)
```sql
mysql> INSERT INTO t1 VALUES  (REPEAT(0125,200000000));
Query OK, 1 row affected, 1 warning (0.00 sec)
 Warning | 1301 | Result of repeat() was larger than max_allowed_packet (67108864) - truncated 
mysql> select * from t1;
+------+
| a    |
+------+
| NULL |
+------+
1 row in set (0.00 sec)
```
### 4. What is your TiDB version? (Required)
```sql
 Release Version: v5.4.0-alpha-67-g17edc5758
Edition: Community
Git Commit Hash: 17edc5758fbf865cada7e156318c41d3ee8a7501
Git Branch: master
UTC Build Time: 2021-11-10 20:45:18
GoVersion: go1.17.2
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false |
```
