ID: 43152
Title: panic in the recoverable goroutine in tidb.log
Description:
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

Checked from tidb.log

### 2. What did you expect to see? (Required)
Some warning and info msg

### 3. What did you see instead (Required)
Intermittently got error as below.

[ERROR] [misc.go:91] ["panic in the recoverable goroutine"] [r="\"send on closed channel\""] ["stack trace"="github.com/pingcap/tidb/util.WithRecovery.func1\n\t/home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/src/github.com/pingcap/tidb/util/misc.go:93\nruntime.gopanic\n\t/usr/local/go/src/runtime/panic.go:679\nruntime.chansend\n\t/usr/local/go/src/runtime/chan.go:187\nruntime.chansend1\n\t/usr/local/go/src/runtime/chan.go:127\ngithub.com/pingcap/tidb/executor.(*indexHashJoinInnerWorker).run\n\t/home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/src/github.com/pingcap/tidb/executor/index_lookup_hash_join.go:503\ngithub.com/pingcap/tidb/executor.(*IndexNestedLoopHashJoin).startWorkers.func2\n\t/home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/src/github.com/pingcap/tidb/executor/index_lookup_hash_join.go:196\ngithub.com/pingcap/tidb/util.WithRecovery\n\t/home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/src/github.com/pingcap/tidb/util/misc.go:96"]


### 4. What is your TiDB version? (Required)

| Release Version: v4.0.9
Edition: Community
Git Commit Hash: 69f05ea55e8409152a7721b2dd8822af011355ea
Git Branch: heads/refs/tags/v4.0.9
UTC Build Time: 2020-12-21 04:26:49
GoVersion: go1.13
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false |


