ID: 59604
Title: br: CI fail due to unexpected gc safepoint
Description:
The CI test `idc-jenkins-ci-tidb/check_dev_2 ` may fail when checking safepoint.
This is because there is gc safepoint registered by other concurrent test.
```
=== RUN   TestOperator

    operator_test.go:80: 

        	Error Trace:	tests/realtikvtest/brietest/operator_test.go:80

        	            				tests/realtikvtest/brietest/operator_test.go:195

        	Error:      	the service gc safepoint exists

        	Test:       	TestOperator

        	Messages:   	it is struct { ServiceID string "json:\"service_id\""; ExpiredAt int64 "json:\"expired_at\""; SafePoint int64 "json:\"safe_point\"" }{ServiceID:"backup-stream-TestPiTRAndBackupInSQL-1", ExpiredAt:1739795773, SafePoint:456075134474649603}

--- FAIL: TestOperator (0.00s)

=== RUN   TestFailure

    operator_test.go:80: 

        	Error Trace:	tests/realtikvtest/brietest/operator_test.go:80

        	            				tests/realtikvtest/brietest/operator_test.go:248

        	Error:      	the service gc safepoint exists

        	Test:       	TestFailure

        	Messages:   	it is struct { ServiceID string "json:\"service_id\""; ExpiredAt int64 "json:\"expired_at\""; SafePoint int64 "json:\"safe_point\"" }{ServiceID:"backup-stream-TestPiTRAndBackupInSQL-1", ExpiredAt:1739795773, SafePoint:456075134474649603}

--- FAIL: TestFailure (0.00s)
```