{
    "sql": "create table A (A Int64, B Int64, S String) Engine=MergeTree order by A as select number, number, toString(arrayMap(i->cityHash64(i*number), range(100))) from numbers(1e7); SET join_algorithm = 'grace_hash', grace_hash_join_initial_buckets=128, grace_hash_join_max_buckets=256; select * from A a join A as b on a.A = b.A limit 1; SET join_algorithm = 'grace_hash', grace_hash_join_initial_buckets=128, grace_hash_join_max_buckets=128; select * from A a join A as b on a.A = b.A limit 1;",
    "Affected Elements": "SET join_algorithm, grace_hash_join_initial_buckets, grace_hash_join_max_buckets, JOIN clause",
    "Root Cause Analysis": "The bug is caused by the attempt to perform a join operation after the data has been released, leading to a logical error in the execution of the join."
}