{
    "sql": "drop table if exists t1, t2; create table t1 (c_int int, c_str varchar(40), c_datetime datetime, c_timestamp timestamp, c_double double, c_decimal decimal(12, 6), unique key(c_int), key(c_timestamp)); create table t2 (c_int int, c_str varchar(40), c_datetime datetime, c_timestamp timestamp, c_double double, c_decimal decimal(12, 6), primary key (c_int), key(c_str), key(c_decimal), key(c_timestamp)) partition by hash (c_int) partitions 4; insert into t1 values (1, 'epic lamport', '2020-05-16 15:59:17', '2020-06-08 00:55:05', 69.828891, 8.031); insert into t1 values (6, 'loving bhaskara', '2020-03-15 11:48:48', '2020-04-24 09:45:29', 14.838255, 5.533), (7, 'quirky zhukovsky', '2020-06-15 17:53:12', '2020-06-12 10:04:02', 5.835174, 9.762); insert into t2 select * from t1; update t1 set c_double = null where (c_int, c_str) in ((7, 'vigorous yonath'), (5, 'eloquent albattani'), (7, 'eloquent kalam'), (10, 'fervent liskov'), (7, 'sleepy hamilton'), (3, 'upbeat bhaskara')) order by c_int, c_str, c_decimal, c_double limit 1; select (select t2.c_double from t2 where t2.c_int = 6 order by t2.c_double limit 1) x from t1;",
    "Affected Elements": "SELECT, UNION, subquery",
    "Root Cause Analysis": "The unexpected additional row in the result set is caused by the presence of duplicate entries in the table t1, leading to multiple rows being returned from the outer query."
}